import {defineArrayMember, defineField, defineType} from 'sanity'

export const mediaItem = defineType({
  name: 'mediaItem',
  title: 'Media Item',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'url',
      title: 'Article URL',
      type: 'url',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sourceName',
      title: 'Source Name',
      type: 'string',
    }),
    defineField({
      name: 'sourceLanguage',
      title: 'Language',
      type: 'string',
      options: {list: ['en', 'zh', 'de', 'ja', 'nl', 'fr']},
    }),
    defineField({
      name: 'description',
      title: 'RSS Snippet (raw)',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'summary',
      title: 'AI Summary',
      type: 'text',
      rows: 4,
      description: 'One-paragraph summary written in the source language (generated by AI from full text)',
    }),
    defineField({
      name: 'keyPoints',
      title: 'Key Points',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      description: '3 key points of trade significance (source language)',
      validation: (Rule) => Rule.max(3),
    }),
    defineField({
      name: 'fullTextFetched',
      title: 'Full Text Fetched',
      type: 'boolean',
      initialValue: false,
      readOnly: true,
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At (original)',
      type: 'datetime',
    }),
    defineField({
      name: 'fetchedAt',
      title: 'Fetched At',
      type: 'datetime',
      readOnly: true,
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          {title: '待分析 Raw', value: 'raw'},
          {title: '✅ 收錄 Collected', value: 'collected'},
          {title: '❌ 排除 Dismissed', value: 'dismissed'},
          {title: '🚫 過濾掉 Filtered Out', value: 'filtered_out'},
        ],
      },
      initialValue: 'raw',
    }),
    defineField({
      name: 'relevanceScore',
      title: 'Relevance Score (0–10)',
      type: 'number',
      validation: (Rule) => Rule.min(0).max(10),
    }),
    defineField({
      name: 'relevanceReason',
      title: 'AI Relevance Reason',
      type: 'text',
      rows: 3,
      readOnly: true,
    }),
    defineField({
      name: 'generatedPost',
      title: 'Generated Post',
      type: 'reference',
      to: [{type: 'post'}],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      status: 'status',
      score: 'relevanceScore',
      source: 'sourceName',
      enriched: 'fullTextFetched',
    },
    prepare({title, status, score, source, enriched}) {
      const statusIcon = status === 'collected' ? '✅' : status === 'dismissed' ? '❌' : status === 'filtered_out' ? '🚫' : '⏳'
      const enrichIcon = enriched ? '📄' : ''
      return {
        title: `${statusIcon}${enrichIcon} ${title ?? '(untitled)'}`,
        subtitle: `${source ?? ''} · score: ${score ?? '—'}`,
      }
    },
  },
})
