import {defineArrayMember, defineField, defineType} from 'sanity'

export const mediaItem = defineType({
  name: 'mediaItem',
  title: 'Media Item',
  type: 'document',
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'url',
      title: 'Article URL',
      type: 'url',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sourceName',
      title: 'Source Name',
      type: 'string',
    }),
    defineField({
      name: 'sourceLanguage',
      title: 'Language',
      type: 'string',
      options: {list: ['en', 'zh', 'de', 'ja', 'nl', 'fr']},
    }),
    defineField({
      name: 'description',
      title: 'RSS Snippet (raw)',
      type: 'text',
      rows: 3,
    }),
    defineField({
      name: 'summary',
      title: 'AI Summary',
      type: 'text',
      rows: 4,
      description: 'One-paragraph summary written in the source language (generated by AI from full text)',
    }),
    defineField({
      name: 'keyPoints',
      title: 'Key Points',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      description: '3 key points of trade significance (source language)',
      validation: (Rule) => Rule.max(3),
    }),
    defineField({
      name: 'fullTextFetched',
      title: 'Full Text Fetched',
      type: 'boolean',
      initialValue: false,
      readOnly: true,
    }),
    defineField({
      name: 'publishedAt',
      title: 'Published At (original)',
      type: 'datetime',
    }),
    defineField({
      name: 'fetchedAt',
      title: 'Fetched At',
      type: 'datetime',
      readOnly: true,
    }),
    defineField({
      name: 'sourceRegion',
      title: '新聞地區',
      type: 'string',
    }),
    defineField({
      name: 'tags',
      title: '標籤',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      options: {
        list: [
          {title: '供應鏈', value: 'supply-chain'},
          {title: '新品發布', value: 'product-launch'},
          {title: '市場動態', value: 'market-news'},
          {title: '法規政策', value: 'regulation'},
          {title: '展覽', value: 'trade-show'},
          {title: '零售通路', value: 'retail'},
          {title: '技術規格', value: 'tech'},
          {title: '電動車', value: 'e-bike'},
          {title: '城市騎行', value: 'urban'},
        ],
        layout: 'tags',
      },
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          {title: '⏳ 待分析', value: 'raw'},
          {title: '🔍 已分析', value: 'analyzed'},
          {title: '✅ 已收錄', value: 'collected'},
          {title: '❌ 已排除', value: 'dismissed'},
        ],
      },
      initialValue: 'raw',
    }),
    defineField({
      name: 'relevanceScore',
      title: 'Relevance Score (0–10)',
      type: 'number',
      validation: (Rule) => Rule.min(0).max(10),
    }),
    defineField({
      name: 'relevanceReason',
      title: 'AI Relevance Reason',
      type: 'text',
      rows: 3,
      readOnly: true,
    }),
    defineField({
      name: 'generatedPost',
      title: 'Generated Post',
      type: 'reference',
      to: [{type: 'post'}],
    }),
  ],
  preview: {
    select: {
      title: 'title',
      status: 'status',
      score: 'relevanceScore',
      source: 'sourceName',
      enriched: 'fullTextFetched',
    },
    prepare({title, status, score, source, enriched}) {
      const statusIcon = status === 'collected' ? '✅' : status === 'analyzed' ? '🔍' : status === 'dismissed' ? '❌' : '⏳'
      const enrichIcon = enriched ? '📄' : ''
      return {
        title: `${statusIcon}${enrichIcon} ${title ?? '(untitled)'}`,
        subtitle: `${source ?? ''} · score: ${score ?? '—'}`,
      }
    },
  },
})
