/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeadline: LocalizedString;
  heroSubtext?: LocalizedText;
  stats?: Array<{
    value?: string;
    label?: LocalizedString;
    _key: string;
  }>;
  joinHeadline?: LocalizedString;
  joinSubtext?: LocalizedText;
  featuredPost?: PostReference;
  featuredBrands?: Array<
    {
      _key: string;
    } & BrandReference
  >;
};

export type LocalizedText = {
  _type: "localizedText";
  en?: string;
  zh?: string;
  ja?: string;
  de?: string;
};

export type LocalizedString = {
  _type: "localizedString";
  en?: string;
  zh?: string;
  ja?: string;
  de?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedString;
  slug: Slug;
  publishedAt: string;
  author?: AuthorReference;
  category?: CategoryReference;
  targetAudience?: Array<string>;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: LocalizedString;
    caption?: LocalizedString;
    _type: "image";
  };
  excerpt?: LocalizedText;
  body?: LocalizedBlockContent;
  featured?: boolean;
  relatedBrands?: Array<
    {
      _key: string;
    } & BrandReference
  >;
};

export type LocalizedBlockContent = {
  _type: "localizedBlockContent";
  en?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  zh?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  ja?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  de?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          blank?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedString;
  slug: Slug;
  description?: LocalizedText;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  website?: string;
  description?: LocalizedText;
  order?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PostReference
  | BrandReference
  | SiteSettings
  | LocalizedText
  | LocalizedString
  | AuthorReference
  | CategoryReference
  | SanityImageAssetReference
  | Post
  | LocalizedBlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | Brand
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries/home.ts
// Variable: homepageQuery
// Query: {  "settings": *[_type == "siteSettings"][0]{    heroEyebrow,    heroHeadline,    heroSubtext,    "stats": stats[]{value, label},    joinHeadline,    joinSubtext,    "featuredPost": featuredPost->{      _id,      title,      slug,      publishedAt,      excerpt,      "mainImage": mainImage{asset->, "alt": alt},      "category": category->{title, slug},      "author": author->{name}    },    "featuredBrands": featuredBrands[]->{_id, name}  },  "recentPosts": *[_type == "post"] | order(publishedAt desc)[0...6]{    _id,    title,    slug,    publishedAt,    excerpt,    "mainImage": mainImage{asset->, "alt": alt},    "category": category->{title, slug},    "author": author->{name}  },  "brands": *[_type == "brand"] | order(order asc)[0...12]{    _id,    name  }}
export type HomepageQueryResult = {
  settings: {
    heroEyebrow: string | null;
    heroHeadline: LocalizedString;
    heroSubtext: LocalizedText | null;
    stats: Array<{
      value: string | null;
      label: LocalizedString | null;
    }> | null;
    joinHeadline: LocalizedString | null;
    joinSubtext: LocalizedText | null;
    featuredPost: {
      _id: string;
      title: LocalizedString;
      slug: Slug;
      publishedAt: string;
      excerpt: LocalizedText | null;
      mainImage: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash: string;
          extension: string;
          mimeType: string;
          size: number;
          assetId: string;
          uploadId?: string;
          path: string;
          url: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        alt: LocalizedString | null;
      } | null;
      category: {
        title: LocalizedString;
        slug: Slug;
      } | null;
      author: {
        name: string;
      } | null;
    } | null;
    featuredBrands: Array<{
      _id: string;
      name: string;
    }> | null;
  } | null;
  recentPosts: Array<{
    _id: string;
    title: LocalizedString;
    slug: Slug;
    publishedAt: string;
    excerpt: LocalizedText | null;
    mainImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      alt: LocalizedString | null;
    } | null;
    category: {
      title: LocalizedString;
      slug: Slug;
    } | null;
    author: {
      name: string;
    } | null;
  }>;
  brands: Array<{
    _id: string;
    name: string;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "settings": *[_type == "siteSettings"][0]{\n    heroEyebrow,\n    heroHeadline,\n    heroSubtext,\n    "stats": stats[]{value, label},\n    joinHeadline,\n    joinSubtext,\n    "featuredPost": featuredPost->{\n      _id,\n      title,\n      slug,\n      publishedAt,\n      excerpt,\n      "mainImage": mainImage{asset->, "alt": alt},\n      "category": category->{title, slug},\n      "author": author->{name}\n    },\n    "featuredBrands": featuredBrands[]->{_id, name}\n  },\n  "recentPosts": *[_type == "post"] | order(publishedAt desc)[0...6]{\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    "mainImage": mainImage{asset->, "alt": alt},\n    "category": category->{title, slug},\n    "author": author->{name}\n  },\n  "brands": *[_type == "brand"] | order(order asc)[0...12]{\n    _id,\n    name\n  }\n}': HomepageQueryResult;
  }
}
